import React, { Component } from 'react'
import axios from 'axios';
import './App.css';
import {
    LineChart,
    Legend, Tooltip,
    Line,
    XAxis,
    YAxis,
    CartesianGrid, 
    ResponsiveContainer
} from 'recharts';
  

class Test3 extends Component {
    state = {
        plots: []
    }
    componentDidMount() {
        axios.get('https://raw.githubusercontent.com/cindyiskandar/Demo-Repo/new_commit/ac_power_output_data.json')
            .then(response => {
                var plots = response.data;
                plots.forEach(element => {
                    element.end_period = new Date(element.end_period)
                    element.end_period = element.end_period.toLocaleTimeString(navigator.language, {
                        hour: '2-digit',
                        minute:'2-digit'
                      });
                });
                this.setState({ plots });                
            });
    }

    render() {
        return (
            <div>
            <p>The estimated power generated by the array in the upcoming 24 hrs is:</p>
            <ResponsiveContainer width="95%" height={300}>
                <LineChart width={730} height={250} data={this.state.plots}
                    margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="end_period" />
                    <YAxis />
                    <Tooltip />
                    <Legend />
                    <Line type="monotone" dataKey="AC_Power" stroke="#8884d8" />
                </LineChart>
                </ResponsiveContainer>
            </div>
        )
    }


}

export default Test3;
